language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install libboost1.55-dev libboost-regex1.55-dev

before_script:
  - mkdir -p build

script:
  - pushd build
  - cmake ..
  - make
  - ./test_suite
  - popd
